on:
  youtube:
    channel_id: UC8Md6Zy3HPN5rHWKhm5qhqg
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.youtube.outputs.title}}
          description: ${{on.youtube.outputs.description}}
          link: ${{on.youtube.outputs.link}}
        run: |
          echo title: $title
          echo description: $description
          echo link: $link
      - name: create-json
        id: create-json-2  # Second ID
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "other.json"
          json: '{"name":$title, "link":$link}'
          dir: 'src/'
